backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
   # === COLECCIÓN PROMOCIONAL (MODIFICADA) ===
  - name: "promocional"
    label: "Imágenes Promocionales"
    files:
      - name: "promocional"
        label: "Imágenes Promocionales"
        file: "content/promocional.json"
        fields:
          - label: "Imágenes"
            name: "imagenes"
            widget: "list"
            fields:
              - { label: "Imagen", name: "imagen", widget: "image", required: false }
              - { label: "Video de YouTube (pegar enlace)", name: "video", widget: "string", required: false, hint: "Ej: https://www.youtube.com/watch?v=ABC123" }
              - { label: "Activa", name: "activa", widget: "boolean", default: true }
  # === COLECCIÓN PARA EL MENÚ (SIMPLIFICADA) ===
  - name: "menu"
    label: "Menú"
    files:
      - name: "pizzas"
        label: "Pizzas"
        file: "content/menu/pizzas.json"
        fields:
          - { label: "Título de la Sección", name: "titulo", widget: "string" }
          - { label: "ID (único, sin espacios)", name: "id", widget: "string" }
          - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
          - label: "Platos"
            name: "platos"
            widget: "list"
            fields:
              - { label: "Nombre del Plato", name: "nombre", widget: "string" }
              - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
              - { label: "Precio", name: "precio", widget: "string" }
          - label: "Subsecciones (opcional)"
            name: "subsecciones"
            widget: "list"
            required: false
            fields:
              - { label: "Título de la Subsección", name: "titulo", widget: "string" }
              - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
              - label: "Platos"
                name: "platos"
                widget: "list"
                fields:
                  - { label: "Nombre del Plato", name: "nombre", widget: "string" }
                  - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
                  - { label: "Precio", name: "precio", widget: "string" }
      - name: "picadas"
        label: "Picadas"
        file: "content/menu/picadas.json"
        fields:
          - { label: "Título de la Sección", name: "titulo", widget: "string" }
          - { label: "ID (único, sin espacios)", name: "id", widget: "string" }
          - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
          - label: "Platos"
            name: "platos"
            widget: "list"
            fields:
              - { label: "Nombre del Plato", name: "nombre", widget: "string" }
              - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
              - { label: "Precio", name: "precio", widget: "string" }
          - label: "Subsecciones (opcional)"
            name: "subsecciones"
            widget: "list"
            required: false
            fields:
              - { label: "Título de la Subsección", name: "titulo", widget: "string" }
              - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
              - label: "Platos"
                name: "platos"
                widget: "list"
                fields:
                  - { label: "Nombre del Plato", name: "nombre", widget: "string" }
                  - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
                  - { label: "Precio", name: "precio", widget: "string" }
      - name: "sandwiches"
        label: "Sandwiches"
        file: "content/menu/sandwiches.json"
        fields:
          - { label: "Título de la Sección", name: "titulo", widget: "string" }
          - { label: "ID (único, sin espacios)", name: "id", widget: "string" }
          - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
          - label: "Platos"
            name: "platos"
            widget: "list"
            fields:
              - { label: "Nombre del Plato", name: "nombre", widget: "string" }
              - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
              - { label: "Precio", name: "precio", widget: "string" }
          - label: "Subsecciones (opcional)"
            name: "subsecciones"
            widget: "list"
            required: false
            fields:
              - { label: "Título de la Subsección", name: "titulo", widget: "string" }
              - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
              - label: "Platos"
                name: "platos"
                widget: "list"
                fields:
                  - { label: "Nombre del Plato", name: "nombre", widget: "string" }
                  - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
                  - { label: "Precio", name: "precio", widget: "string" }
      - name: "hamburguesas"
        label: "Hamburguesas"
        file: "content/menu/hamburguesas.json"
        fields:
          - { label: "Título de la Sección", name: "titulo", widget: "string" }
          - { label: "ID (único, sin espacios)", name: "id", widget: "string" }
          - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
          - label: "Platos"
            name: "platos"
            widget: "list"
            fields:
              - { label: "Nombre del Plato", name: "nombre", widget: "string" }
              - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
              - { label: "Precio", name: "precio", widget: "string" }
          - label: "Subsecciones (opcional)"
            name: "subsecciones"
            widget: "list"
            required: false
            fields:
              - { label: "Título de la Subsección", name: "titulo", widget: "string" }
              - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
              - label: "Platos"
                name: "platos"
                widget: "list"
                fields:
                  - { label: "Nombre del Plato", name: "nombre", widget: "string" }
                  - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
                  - { label: "Precio", name: "precio", widget: "string" }
      - name: "papas"
        label: "Papas"
        file: "content/menu/papas.json"
        fields:
          - { label: "Título de la Sección", name: "titulo", widget: "string" }
          - { label: "ID (único, sin espacios)", name: "id", widget: "string" }
          - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
          - label: "Platos"
            name: "platos"
            widget: "list"
            fields:
              - { label: "Nombre del Plato", name: "nombre", widget: "string" }
              - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
              - { label: "Precio", name: "precio", widget: "string" }
          - label: "Subsecciones (opcional)"
            name: "subsecciones"
            widget: "list"
            required: false
            fields:
              - { label: "Título de la Subsección", name: "titulo", widget: "string" }
              - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
              - label: "Platos"
                name: "platos"
                widget: "list"
                fields:
                  - { label: "Nombre del Plato", name: "nombre", widget: "string" }
                  - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
                  - { label: "Precio", name: "precio", widget: "string" }
      - name: "empanadas"
        label: "Empanadas"
        file: "content/menu/empanadas.json"
        fields:
          - { label: "Título de la Sección", name: "titulo", widget: "string" }
          - { label: "ID (único, sin espacios)", name: "id", widget: "string" }
          - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
          - label: "Platos"
            name: "platos"
            widget: "list"
            fields:
              - { label: "Nombre del Plato", name: "nombre", widget: "string" }
              - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
              - { label: "Precio", name: "precio", widget: "string" }
          - label: "Subsecciones (opcional)"
            name: "subsecciones"
            widget: "list"
            required: false
            fields:
              - { label: "Título de la Subsección", name: "titulo", widget: "string" }
              - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
              - label: "Platos"
                name: "platos"
                widget: "list"
                fields:
                  - { label: "Nombre del Plato", name: "nombre", widget: "string" }
                  - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
                  - { label: "Precio", name: "precio", widget: "string" }
      - name: "bebidas"
        label: "Bebidas"
        file: "content/menu/bebidas.json"
        fields:
          - { label: "Título de la Sección", name: "titulo", widget: "string" }
          - { label: "ID (único, sin espacios)", name: "id", widget: "string" }
          - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
          - label: "Platos"
            name: "platos"
            widget: "list"
            fields:
              - { label: "Nombre del Plato", name: "nombre", widget: "string" }
              - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
              - { label: "Precio", name: "precio", widget: "string" }
          - label: "Subsecciones (opcional)"
            name: "subsecciones"
            widget: "list"
            required: false
            fields:
              - { label: "Título de la Subsección", name: "titulo", widget: "string" }
              - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
              - label: "Platos"
                name: "platos"
                widget: "list"
                fields:
                  - { label: "Nombre del Plato", name: "nombre", widget: "string" }
                  - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
                  - { label: "Precio", name: "precio", widget: "string" }
      - name: "tragos"
        label: "Tragos"
        file: "content/menu/tragos.json"
        fields:
          - { label: "Título de la Sección", name: "titulo", widget: "string" }
          - { label: "ID (único, sin espacios)", name: "id", widget: "string" }
          - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
          - label: "Platos"
            name: "platos"
            widget: "list"
            fields:
              - { label: "Nombre del Plato", name: "nombre", widget: "string" }
              - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
              - { label: "Precio", name: "precio", widget: "string" }
          - label: "Subsecciones (opcional)"
            name: "subsecciones"
            widget: "list"
            required: false
            fields:
              - { label: "Título de la Subsección", name: "titulo", widget: "string" }
              - { label: "Nota (opcional)", name: "nota", widget: "text", required: false }
              - label: "Platos"
                name: "platos"
                widget: "list"
                fields:
                  - { label: "Nombre del Plato", name: "nombre", widget: "string" }
                  - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
                  - { label: "Precio", name: "precio", widget: "string" }